export const STATIC_DATA = {
    "Global": {
      "NewConfirmed": 109895,
      "TotalConfirmed": 7215417,
      "NewDeaths": 3825,
      "TotalDeaths": 414415,
      "NewRecovered": 152647,
      "TotalRecovered": 3292916
    },
    "Countries": [
      {
        "Country": "Afghanistan",
        "CountryCode": "AF",
        "Slug": "afghanistan",
        "NewConfirmed": 575,
        "TotalConfirmed": 20917,
        "NewDeaths": 12,
        "TotalDeaths": 369,
        "NewRecovered": 296,
        "TotalRecovered": 2171,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Albania",
        "CountryCode": "AL",
        "Slug": "albania",
        "NewConfirmed": 17,
        "TotalConfirmed": 1263,
        "NewDeaths": 0,
        "TotalDeaths": 34,
        "NewRecovered": 7,
        "TotalRecovered": 945,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Algeria",
        "CountryCode": "DZ",
        "Slug": "algeria",
        "NewConfirmed": 111,
        "TotalConfirmed": 10265,
        "NewDeaths": 8,
        "TotalDeaths": 715,
        "NewRecovered": 82,
        "TotalRecovered": 6799,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Andorra",
        "CountryCode": "AD",
        "Slug": "andorra",
        "NewConfirmed": 0,
        "TotalConfirmed": 852,
        "NewDeaths": 0,
        "TotalDeaths": 51,
        "NewRecovered": 7,
        "TotalRecovered": 751,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Angola",
        "CountryCode": "AO",
        "Slug": "angola",
        "NewConfirmed": 1,
        "TotalConfirmed": 92,
        "NewDeaths": 0,
        "TotalDeaths": 4,
        "NewRecovered": 14,
        "TotalRecovered": 38,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Antigua and Barbuda",
        "CountryCode": "AG",
        "Slug": "antigua-and-barbuda",
        "NewConfirmed": 0,
        "TotalConfirmed": 26,
        "NewDeaths": 0,
        "TotalDeaths": 3,
        "NewRecovered": 0,
        "TotalRecovered": 20,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Argentina",
        "CountryCode": "AR",
        "Slug": "argentina",
        "NewConfirmed": 826,
        "TotalConfirmed": 23620,
        "NewDeaths": 29,
        "TotalDeaths": 693,
        "NewRecovered": 396,
        "TotalRecovered": 7305,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Armenia",
        "CountryCode": "AM",
        "Slug": "armenia",
        "NewConfirmed": 195,
        "TotalConfirmed": 13325,
        "NewDeaths": 11,
        "TotalDeaths": 211,
        "NewRecovered": 85,
        "TotalRecovered": 4099,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Australia",
        "CountryCode": "AU",
        "Slug": "australia",
        "NewConfirmed": 2,
        "TotalConfirmed": 7267,
        "NewDeaths": 0,
        "TotalDeaths": 102,
        "NewRecovered": 14,
        "TotalRecovered": 6720,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Austria",
        "CountryCode": "AT",
        "Slug": "austria",
        "NewConfirmed": 66,
        "TotalConfirmed": 16968,
        "NewDeaths": 0,
        "TotalDeaths": 672,
        "NewRecovered": 46,
        "TotalRecovered": 15839,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Azerbaijan",
        "CountryCode": "AZ",
        "Slug": "azerbaijan",
        "NewConfirmed": 323,
        "TotalConfirmed": 7876,
        "NewDeaths": 5,
        "TotalDeaths": 93,
        "NewRecovered": 228,
        "TotalRecovered": 4377,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Bahamas",
        "CountryCode": "BS",
        "Slug": "bahamas",
        "NewConfirmed": 0,
        "TotalConfirmed": 103,
        "NewDeaths": 0,
        "TotalDeaths": 11,
        "NewRecovered": 2,
        "TotalRecovered": 64,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Bahrain",
        "CountryCode": "BH",
        "Slug": "bahrain",
        "NewConfirmed": 654,
        "TotalConfirmed": 15417,
        "NewDeaths": 1,
        "TotalDeaths": 27,
        "NewRecovered": 858,
        "TotalRecovered": 10326,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Bangladesh",
        "CountryCode": "BD",
        "Slug": "bangladesh",
        "NewConfirmed": 2735,
        "TotalConfirmed": 68504,
        "NewDeaths": 42,
        "TotalDeaths": 930,
        "NewRecovered": 657,
        "TotalRecovered": 14560,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Barbados",
        "CountryCode": "BB",
        "Slug": "barbados",
        "NewConfirmed": 0,
        "TotalConfirmed": 92,
        "NewDeaths": 0,
        "TotalDeaths": 7,
        "NewRecovered": 0,
        "TotalRecovered": 81,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Belarus",
        "CountryCode": "BY",
        "Slug": "belarus",
        "NewConfirmed": 823,
        "TotalConfirmed": 49453,
        "NewDeaths": 7,
        "TotalDeaths": 276,
        "NewRecovered": 233,
        "TotalRecovered": 23880,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Belgium",
        "CountryCode": "BE",
        "Slug": "belgium",
        "NewConfirmed": 122,
        "TotalConfirmed": 59348,
        "NewDeaths": 11,
        "TotalDeaths": 9606,
        "NewRecovered": 24,
        "TotalRecovered": 16315,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Belize",
        "CountryCode": "BZ",
        "Slug": "belize",
        "NewConfirmed": 0,
        "TotalConfirmed": 19,
        "NewDeaths": 0,
        "TotalDeaths": 2,
        "NewRecovered": 0,
        "TotalRecovered": 16,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Benin",
        "CountryCode": "BJ",
        "Slug": "benin",
        "NewConfirmed": 27,
        "TotalConfirmed": 288,
        "NewDeaths": 1,
        "TotalDeaths": 4,
        "NewRecovered": 35,
        "TotalRecovered": 186,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Bhutan",
        "CountryCode": "BT",
        "Slug": "bhutan",
        "NewConfirmed": 0,
        "TotalConfirmed": 59,
        "NewDeaths": 0,
        "TotalDeaths": 0,
        "NewRecovered": 3,
        "TotalRecovered": 14,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Bolivia",
        "CountryCode": "BO",
        "Slug": "bolivia",
        "NewConfirmed": 306,
        "TotalConfirmed": 13949,
        "NewDeaths": 10,
        "TotalDeaths": 475,
        "NewRecovered": 73,
        "TotalRecovered": 2159,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Bosnia and Herzegovina",
        "CountryCode": "BA",
        "Slug": "bosnia-and-herzegovina",
        "NewConfirmed": 98,
        "TotalConfirmed": 2704,
        "NewDeaths": 1,
        "TotalDeaths": 160,
        "NewRecovered": 55,
        "TotalRecovered": 2023,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Botswana",
        "CountryCode": "BW",
        "Slug": "botswana",
        "NewConfirmed": 2,
        "TotalConfirmed": 42,
        "NewDeaths": 0,
        "TotalDeaths": 1,
        "NewRecovered": 1,
        "TotalRecovered": 24,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Brazil",
        "CountryCode": "BR",
        "Slug": "brazil",
        "NewConfirmed": 15654,
        "TotalConfirmed": 707412,
        "NewDeaths": 679,
        "TotalDeaths": 37134,
        "NewRecovered": 94305,
        "TotalRecovered": 378257,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Brunei Darussalam",
        "CountryCode": "BN",
        "Slug": "brunei",
        "NewConfirmed": 0,
        "TotalConfirmed": 141,
        "NewDeaths": 0,
        "TotalDeaths": 2,
        "NewRecovered": 0,
        "TotalRecovered": 138,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Bulgaria",
        "CountryCode": "BG",
        "Slug": "bulgaria",
        "NewConfirmed": 83,
        "TotalConfirmed": 2810,
        "NewDeaths": 4,
        "TotalDeaths": 164,
        "NewRecovered": 39,
        "TotalRecovered": 1587,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Burkina Faso",
        "CountryCode": "BF",
        "Slug": "burkina-faso",
        "NewConfirmed": 1,
        "TotalConfirmed": 890,
        "NewDeaths": 0,
        "TotalDeaths": 53,
        "NewRecovered": 0,
        "TotalRecovered": 765,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Burundi",
        "CountryCode": "BI",
        "Slug": "burundi",
        "NewConfirmed": 0,
        "TotalConfirmed": 83,
        "NewDeaths": 0,
        "TotalDeaths": 1,
        "NewRecovered": 0,
        "TotalRecovered": 45,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Cambodia",
        "CountryCode": "KH",
        "Slug": "cambodia",
        "NewConfirmed": 0,
        "TotalConfirmed": 126,
        "NewDeaths": 0,
        "TotalDeaths": 0,
        "NewRecovered": 0,
        "TotalRecovered": 123,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Cameroon",
        "CountryCode": "CM",
        "Slug": "cameroon",
        "NewConfirmed": 152,
        "TotalConfirmed": 8060,
        "NewDeaths": 0,
        "TotalDeaths": 212,
        "NewRecovered": 13,
        "TotalRecovered": 4748,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Canada",
        "CountryCode": "CA",
        "Slug": "canada",
        "NewConfirmed": 1090,
        "TotalConfirmed": 195446,
        "NewDeaths": 66,
        "TotalDeaths": 15818,
        "NewRecovered": 668,
        "TotalRecovered": 55343,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Cape Verde",
        "CountryCode": "CV",
        "Slug": "cape-verde",
        "NewConfirmed": 13,
        "TotalConfirmed": 567,
        "NewDeaths": 0,
        "TotalDeaths": 5,
        "NewRecovered": 26,
        "TotalRecovered": 266,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Central African Republic",
        "CountryCode": "CF",
        "Slug": "central-african-republic",
        "NewConfirmed": 216,
        "TotalConfirmed": 1850,
        "NewDeaths": 0,
        "TotalDeaths": 5,
        "NewRecovered": 0,
        "TotalRecovered": 38,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Chad",
        "CountryCode": "TD",
        "Slug": "chad",
        "NewConfirmed": 2,
        "TotalConfirmed": 839,
        "NewDeaths": 1,
        "TotalDeaths": 70,
        "NewRecovered": 13,
        "TotalRecovered": 685,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Chile",
        "CountryCode": "CL",
        "Slug": "chile",
        "NewConfirmed": 4696,
        "TotalConfirmed": 138846,
        "NewDeaths": 627,
        "TotalDeaths": 2264,
        "NewRecovered": 4098,
        "TotalRecovered": 112248,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "China",
        "CountryCode": "CN",
        "Slug": "china",
        "NewConfirmed": 4,
        "TotalConfirmed": 84195,
        "NewDeaths": 0,
        "TotalDeaths": 4638,
        "NewRecovered": 10,
        "TotalRecovered": 79444,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Colombia",
        "CountryCode": "CO",
        "Slug": "colombia",
        "NewConfirmed": 2698,
        "TotalConfirmed": 40847,
        "NewDeaths": 108,
        "TotalDeaths": 1373,
        "NewRecovered": 2045,
        "TotalRecovered": 16459,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Comoros",
        "CountryCode": "KM",
        "Slug": "comoros",
        "NewConfirmed": 0,
        "TotalConfirmed": 141,
        "NewDeaths": 0,
        "TotalDeaths": 2,
        "NewRecovered": 0,
        "TotalRecovered": 67,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Congo (Brazzaville)",
        "CountryCode": "CG",
        "Slug": "congo-brazzaville",
        "NewConfirmed": 0,
        "TotalConfirmed": 683,
        "NewDeaths": 0,
        "TotalDeaths": 22,
        "NewRecovered": 0,
        "TotalRecovered": 210,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Congo (Kinshasa)",
        "CountryCode": "CD",
        "Slug": "congo-kinshasa",
        "NewConfirmed": 90,
        "TotalConfirmed": 4106,
        "NewDeaths": 3,
        "TotalDeaths": 88,
        "NewRecovered": 0,
        "TotalRecovered": 537,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Costa Rica",
        "CountryCode": "CR",
        "Slug": "costa-rica",
        "NewConfirmed": 24,
        "TotalConfirmed": 1342,
        "NewDeaths": 1,
        "TotalDeaths": 11,
        "NewRecovered": 8,
        "TotalRecovered": 712,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Croatia",
        "CountryCode": "HR",
        "Slug": "croatia",
        "NewConfirmed": 0,
        "TotalConfirmed": 2247,
        "NewDeaths": 0,
        "TotalDeaths": 104,
        "NewRecovered": 2,
        "TotalRecovered": 2128,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Cuba",
        "CountryCode": "CU",
        "Slug": "cuba",
        "NewConfirmed": 9,
        "TotalConfirmed": 2200,
        "NewDeaths": 0,
        "TotalDeaths": 83,
        "NewRecovered": 6,
        "TotalRecovered": 1868,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Cyprus",
        "CountryCode": "CY",
        "Slug": "cyprus",
        "NewConfirmed": 6,
        "TotalConfirmed": 970,
        "NewDeaths": 0,
        "TotalDeaths": 18,
        "NewRecovered": 0,
        "TotalRecovered": 807,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Czech Republic",
        "CountryCode": "CZ",
        "Slug": "czech-republic",
        "NewConfirmed": 69,
        "TotalConfirmed": 9697,
        "NewDeaths": 1,
        "TotalDeaths": 328,
        "NewRecovered": 103,
        "TotalRecovered": 6994,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Côte d'Ivoire",
        "CountryCode": "CI",
        "Slug": "cote-divoire",
        "NewConfirmed": 142,
        "TotalConfirmed": 3881,
        "NewDeaths": 2,
        "TotalDeaths": 38,
        "NewRecovered": 51,
        "TotalRecovered": 1869,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Denmark",
        "CountryCode": "DK",
        "Slug": "denmark",
        "NewConfirmed": 14,
        "TotalConfirmed": 12162,
        "NewDeaths": 4,
        "TotalDeaths": 593,
        "NewRecovered": 37,
        "TotalRecovered": 10992,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Djibouti",
        "CountryCode": "DJ",
        "Slug": "djibouti",
        "NewConfirmed": 71,
        "TotalConfirmed": 4278,
        "NewDeaths": 3,
        "TotalDeaths": 31,
        "NewRecovered": 136,
        "TotalRecovered": 2013,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Dominica",
        "CountryCode": "DM",
        "Slug": "dominica",
        "NewConfirmed": 0,
        "TotalConfirmed": 18,
        "NewDeaths": 0,
        "TotalDeaths": 0,
        "NewRecovered": 0,
        "TotalRecovered": 16,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Dominican Republic",
        "CountryCode": "DO",
        "Slug": "dominican-republic",
        "NewConfirmed": 526,
        "TotalConfirmed": 20126,
        "NewDeaths": 1,
        "TotalDeaths": 539,
        "NewRecovered": 151,
        "TotalRecovered": 12158,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Ecuador",
        "CountryCode": "EC",
        "Slug": "ecuador",
        "NewConfirmed": 258,
        "TotalConfirmed": 43378,
        "NewDeaths": 21,
        "TotalDeaths": 3642,
        "NewRecovered": 0,
        "TotalRecovered": 21020,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Egypt",
        "CountryCode": "EG",
        "Slug": "egypt",
        "NewConfirmed": 1365,
        "TotalConfirmed": 35444,
        "NewDeaths": 34,
        "TotalDeaths": 1271,
        "NewRecovered": 414,
        "TotalRecovered": 9375,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "El Salvador",
        "CountryCode": "SV",
        "Slug": "el-salvador",
        "NewConfirmed": 89,
        "TotalConfirmed": 3104,
        "NewDeaths": 3,
        "TotalDeaths": 56,
        "NewRecovered": 74,
        "TotalRecovered": 1379,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Equatorial Guinea",
        "CountryCode": "GQ",
        "Slug": "equatorial-guinea",
        "NewConfirmed": 0,
        "TotalConfirmed": 1306,
        "NewDeaths": 0,
        "TotalDeaths": 12,
        "NewRecovered": 0,
        "TotalRecovered": 200,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Eritrea",
        "CountryCode": "ER",
        "Slug": "eritrea",
        "NewConfirmed": 0,
        "TotalConfirmed": 39,
        "NewDeaths": 0,
        "TotalDeaths": 0,
        "NewRecovered": 0,
        "TotalRecovered": 39,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Estonia",
        "CountryCode": "EE",
        "Slug": "estonia",
        "NewConfirmed": 1,
        "TotalConfirmed": 1940,
        "NewDeaths": 0,
        "TotalDeaths": 69,
        "NewRecovered": 2,
        "TotalRecovered": 1683,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Ethiopia",
        "CountryCode": "ET",
        "Slug": "ethiopia",
        "NewConfirmed": 136,
        "TotalConfirmed": 2156,
        "NewDeaths": 0,
        "TotalDeaths": 27,
        "NewRecovered": 17,
        "TotalRecovered": 361,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Fiji",
        "CountryCode": "FJ",
        "Slug": "fiji",
        "NewConfirmed": 0,
        "TotalConfirmed": 18,
        "NewDeaths": 0,
        "TotalDeaths": 0,
        "NewRecovered": 0,
        "TotalRecovered": 18,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Finland",
        "CountryCode": "FI",
        "Slug": "finland",
        "NewConfirmed": 20,
        "TotalConfirmed": 7001,
        "NewDeaths": 0,
        "TotalDeaths": 323,
        "NewRecovered": 0,
        "TotalRecovered": 5800,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "France",
        "CountryCode": "FR",
        "Slug": "france",
        "NewConfirmed": 211,
        "TotalConfirmed": 191313,
        "NewDeaths": 54,
        "TotalDeaths": 29212,
        "NewRecovered": 221,
        "TotalRecovered": 71182,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Gabon",
        "CountryCode": "GA",
        "Slug": "gabon",
        "NewConfirmed": 0,
        "TotalConfirmed": 3101,
        "NewDeaths": 0,
        "TotalDeaths": 21,
        "NewRecovered": 0,
        "TotalRecovered": 833,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Gambia",
        "CountryCode": "GM",
        "Slug": "gambia",
        "NewConfirmed": 2,
        "TotalConfirmed": 28,
        "NewDeaths": 0,
        "TotalDeaths": 1,
        "NewRecovered": 0,
        "TotalRecovered": 21,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Georgia",
        "CountryCode": "GE",
        "Slug": "georgia",
        "NewConfirmed": 3,
        "TotalConfirmed": 812,
        "NewDeaths": 0,
        "TotalDeaths": 13,
        "NewRecovered": 9,
        "TotalRecovered": 683,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Germany",
        "CountryCode": "DE",
        "Slug": "germany",
        "NewConfirmed": 359,
        "TotalConfirmed": 186109,
        "NewDeaths": 10,
        "TotalDeaths": 8695,
        "NewRecovered": 332,
        "TotalRecovered": 169556,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Ghana",
        "CountryCode": "GH",
        "Slug": "ghana",
        "NewConfirmed": 272,
        "TotalConfirmed": 9910,
        "NewDeaths": 4,
        "TotalDeaths": 48,
        "NewRecovered": 9,
        "TotalRecovered": 3645,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Greece",
        "CountryCode": "GR",
        "Slug": "greece",
        "NewConfirmed": 52,
        "TotalConfirmed": 3049,
        "NewDeaths": 2,
        "TotalDeaths": 182,
        "NewRecovered": 0,
        "TotalRecovered": 1374,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Grenada",
        "CountryCode": "GD",
        "Slug": "grenada",
        "NewConfirmed": 0,
        "TotalConfirmed": 23,
        "NewDeaths": 0,
        "TotalDeaths": 0,
        "NewRecovered": 0,
        "TotalRecovered": 22,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Guatemala",
        "CountryCode": "GT",
        "Slug": "guatemala",
        "NewConfirmed": 447,
        "TotalConfirmed": 7502,
        "NewDeaths": 15,
        "TotalDeaths": 267,
        "NewRecovered": 62,
        "TotalRecovered": 1323,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Guinea",
        "CountryCode": "GN",
        "Slug": "guinea",
        "NewConfirmed": 99,
        "TotalConfirmed": 4216,
        "NewDeaths": 0,
        "TotalDeaths": 23,
        "NewRecovered": 41,
        "TotalRecovered": 2918,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Guinea-Bissau",
        "CountryCode": "GW",
        "Slug": "guinea-bissau",
        "NewConfirmed": 21,
        "TotalConfirmed": 1389,
        "NewDeaths": 0,
        "TotalDeaths": 12,
        "NewRecovered": 0,
        "TotalRecovered": 153,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Guyana",
        "CountryCode": "GY",
        "Slug": "guyana",
        "NewConfirmed": 0,
        "TotalConfirmed": 154,
        "NewDeaths": 0,
        "TotalDeaths": 12,
        "NewRecovered": 4,
        "TotalRecovered": 84,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Haiti",
        "CountryCode": "HT",
        "Slug": "haiti",
        "NewConfirmed": 204,
        "TotalConfirmed": 3538,
        "NewDeaths": 3,
        "TotalDeaths": 54,
        "NewRecovered": 0,
        "TotalRecovered": 24,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Holy See (Vatican City State)",
        "CountryCode": "VA",
        "Slug": "holy-see-vatican-city-state",
        "NewConfirmed": 0,
        "TotalConfirmed": 12,
        "NewDeaths": 0,
        "TotalDeaths": 0,
        "NewRecovered": 0,
        "TotalRecovered": 12,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Honduras",
        "CountryCode": "HN",
        "Slug": "honduras",
        "NewConfirmed": 123,
        "TotalConfirmed": 6450,
        "NewDeaths": 4,
        "TotalDeaths": 262,
        "NewRecovered": 28,
        "TotalRecovered": 740,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Hungary",
        "CountryCode": "HU",
        "Slug": "hungary",
        "NewConfirmed": 6,
        "TotalConfirmed": 4014,
        "NewDeaths": 2,
        "TotalDeaths": 548,
        "NewRecovered": 5,
        "TotalRecovered": 2284,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Iceland",
        "CountryCode": "IS",
        "Slug": "iceland",
        "NewConfirmed": 0,
        "TotalConfirmed": 1807,
        "NewDeaths": 0,
        "TotalDeaths": 10,
        "NewRecovered": 0,
        "TotalRecovered": 1794,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "India",
        "CountryCode": "IN",
        "Slug": "india",
        "NewConfirmed": 8442,
        "TotalConfirmed": 265928,
        "NewDeaths": 266,
        "TotalDeaths": 7473,
        "NewRecovered": 5247,
        "TotalRecovered": 129095,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Indonesia",
        "CountryCode": "ID",
        "Slug": "indonesia",
        "NewConfirmed": 847,
        "TotalConfirmed": 32033,
        "NewDeaths": 32,
        "TotalDeaths": 1883,
        "NewRecovered": 406,
        "TotalRecovered": 10904,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Iran, Islamic Republic of",
        "CountryCode": "IR",
        "Slug": "iran",
        "NewConfirmed": 2043,
        "TotalConfirmed": 173832,
        "NewDeaths": 70,
        "TotalDeaths": 8351,
        "NewRecovered": 2011,
        "TotalRecovered": 136360,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Iraq",
        "CountryCode": "IQ",
        "Slug": "iraq",
        "NewConfirmed": 1115,
        "TotalConfirmed": 13481,
        "NewDeaths": 24,
        "TotalDeaths": 370,
        "NewRecovered": 386,
        "TotalRecovered": 5572,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Ireland",
        "CountryCode": "IE",
        "Slug": "ireland",
        "NewConfirmed": 6,
        "TotalConfirmed": 25207,
        "NewDeaths": 4,
        "TotalDeaths": 1683,
        "NewRecovered": 0,
        "TotalRecovered": 22698,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Israel",
        "CountryCode": "IL",
        "Slug": "israel",
        "NewConfirmed": 169,
        "TotalConfirmed": 18032,
        "NewDeaths": 0,
        "TotalDeaths": 298,
        "NewRecovered": 11,
        "TotalRecovered": 15102,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Italy",
        "CountryCode": "IT",
        "Slug": "italy",
        "NewConfirmed": 280,
        "TotalConfirmed": 235278,
        "NewDeaths": 65,
        "TotalDeaths": 33964,
        "NewRecovered": 747,
        "TotalRecovered": 166584,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Jamaica",
        "CountryCode": "JM",
        "Slug": "jamaica",
        "NewConfirmed": 1,
        "TotalConfirmed": 599,
        "NewDeaths": 0,
        "TotalDeaths": 10,
        "NewRecovered": 0,
        "TotalRecovered": 405,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Japan",
        "CountryCode": "JP",
        "Slug": "japan",
        "NewConfirmed": 21,
        "TotalConfirmed": 17060,
        "NewDeaths": 3,
        "TotalDeaths": 920,
        "NewRecovered": 53,
        "TotalRecovered": 15043,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Jordan",
        "CountryCode": "JO",
        "Slug": "jordan",
        "NewConfirmed": 23,
        "TotalConfirmed": 831,
        "NewDeaths": 0,
        "TotalDeaths": 9,
        "NewRecovered": 20,
        "TotalRecovered": 627,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Kazakhstan",
        "CountryCode": "KZ",
        "Slug": "kazakhstan",
        "NewConfirmed": 165,
        "TotalConfirmed": 12859,
        "NewDeaths": 0,
        "TotalDeaths": 56,
        "NewRecovered": 0,
        "TotalRecovered": 7376,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Kenya",
        "CountryCode": "KE",
        "Slug": "kenya",
        "NewConfirmed": 105,
        "TotalConfirmed": 2872,
        "NewDeaths": 1,
        "TotalDeaths": 85,
        "NewRecovered": 97,
        "TotalRecovered": 849,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Korea (South)",
        "CountryCode": "KR",
        "Slug": "korea-south",
        "NewConfirmed": 38,
        "TotalConfirmed": 11852,
        "NewDeaths": 1,
        "TotalDeaths": 274,
        "NewRecovered": 26,
        "TotalRecovered": 10589,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Kuwait",
        "CountryCode": "KW",
        "Slug": "kuwait",
        "NewConfirmed": 662,
        "TotalConfirmed": 32510,
        "NewDeaths": 5,
        "TotalDeaths": 269,
        "NewRecovered": 1037,
        "TotalRecovered": 21242,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Kyrgyzstan",
        "CountryCode": "KG",
        "Slug": "kyrgyzstan",
        "NewConfirmed": 25,
        "TotalConfirmed": 2032,
        "NewDeaths": 1,
        "TotalDeaths": 23,
        "NewRecovered": 20,
        "TotalRecovered": 1445,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Lao PDR",
        "CountryCode": "LA",
        "Slug": "lao-pdr",
        "NewConfirmed": 0,
        "TotalConfirmed": 19,
        "NewDeaths": 0,
        "TotalDeaths": 0,
        "NewRecovered": 0,
        "TotalRecovered": 18,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Latvia",
        "CountryCode": "LV",
        "Slug": "latvia",
        "NewConfirmed": 0,
        "TotalConfirmed": 1088,
        "NewDeaths": 1,
        "TotalDeaths": 26,
        "NewRecovered": 0,
        "TotalRecovered": 781,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Lebanon",
        "CountryCode": "LB",
        "Slug": "lebanon",
        "NewConfirmed": 19,
        "TotalConfirmed": 1350,
        "NewDeaths": 0,
        "TotalDeaths": 30,
        "NewRecovered": 11,
        "TotalRecovered": 779,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Lesotho",
        "CountryCode": "LS",
        "Slug": "lesotho",
        "NewConfirmed": 0,
        "TotalConfirmed": 4,
        "NewDeaths": 0,
        "TotalDeaths": 0,
        "NewRecovered": 0,
        "TotalRecovered": 2,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Liberia",
        "CountryCode": "LR",
        "Slug": "liberia",
        "NewConfirmed": 11,
        "TotalConfirmed": 370,
        "NewDeaths": 0,
        "TotalDeaths": 30,
        "NewRecovered": 1,
        "TotalRecovered": 195,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Libya",
        "CountryCode": "LY",
        "Slug": "libya",
        "NewConfirmed": 76,
        "TotalConfirmed": 332,
        "NewDeaths": 0,
        "TotalDeaths": 5,
        "NewRecovered": 5,
        "TotalRecovered": 57,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Liechtenstein",
        "CountryCode": "LI",
        "Slug": "liechtenstein",
        "NewConfirmed": 0,
        "TotalConfirmed": 82,
        "NewDeaths": 0,
        "TotalDeaths": 1,
        "NewRecovered": 0,
        "TotalRecovered": 55,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Lithuania",
        "CountryCode": "LT",
        "Slug": "lithuania",
        "NewConfirmed": 6,
        "TotalConfirmed": 1720,
        "NewDeaths": 0,
        "TotalDeaths": 71,
        "NewRecovered": 3,
        "TotalRecovered": 1331,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Luxembourg",
        "CountryCode": "LU",
        "Slug": "luxembourg",
        "NewConfirmed": 1,
        "TotalConfirmed": 4040,
        "NewDeaths": 0,
        "TotalDeaths": 110,
        "NewRecovered": 2,
        "TotalRecovered": 3901,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Macedonia, Republic of",
        "CountryCode": "MK",
        "Slug": "macedonia",
        "NewConfirmed": 127,
        "TotalConfirmed": 3152,
        "NewDeaths": 3,
        "TotalDeaths": 156,
        "NewRecovered": 7,
        "TotalRecovered": 1653,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Madagascar",
        "CountryCode": "MG",
        "Slug": "madagascar",
        "NewConfirmed": 42,
        "TotalConfirmed": 1094,
        "NewDeaths": 0,
        "TotalDeaths": 9,
        "NewRecovered": 21,
        "TotalRecovered": 254,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Malawi",
        "CountryCode": "MW",
        "Slug": "malawi",
        "NewConfirmed": 5,
        "TotalConfirmed": 443,
        "NewDeaths": 0,
        "TotalDeaths": 4,
        "NewRecovered": 0,
        "TotalRecovered": 55,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Malaysia",
        "CountryCode": "MY",
        "Slug": "malaysia",
        "NewConfirmed": 7,
        "TotalConfirmed": 8329,
        "NewDeaths": 0,
        "TotalDeaths": 117,
        "NewRecovered": 20,
        "TotalRecovered": 6694,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Maldives",
        "CountryCode": "MV",
        "Slug": "maldives",
        "NewConfirmed": 13,
        "TotalConfirmed": 1916,
        "NewDeaths": 0,
        "TotalDeaths": 8,
        "NewRecovered": 98,
        "TotalRecovered": 925,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Mali",
        "CountryCode": "ML",
        "Slug": "mali",
        "NewConfirmed": 14,
        "TotalConfirmed": 1547,
        "NewDeaths": 2,
        "TotalDeaths": 92,
        "NewRecovered": 43,
        "TotalRecovered": 916,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Malta",
        "CountryCode": "MT",
        "Slug": "malta",
        "NewConfirmed": 1,
        "TotalConfirmed": 630,
        "NewDeaths": 0,
        "TotalDeaths": 9,
        "NewRecovered": 0,
        "TotalRecovered": 596,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Mauritania",
        "CountryCode": "MR",
        "Slug": "mauritania",
        "NewConfirmed": 55,
        "TotalConfirmed": 1104,
        "NewDeaths": 4,
        "TotalDeaths": 59,
        "NewRecovered": 11,
        "TotalRecovered": 119,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Mauritius",
        "CountryCode": "MU",
        "Slug": "mauritius",
        "NewConfirmed": 0,
        "TotalConfirmed": 337,
        "NewDeaths": 0,
        "TotalDeaths": 10,
        "NewRecovered": 0,
        "TotalRecovered": 324,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Mexico",
        "CountryCode": "MX",
        "Slug": "mexico",
        "NewConfirmed": 2999,
        "TotalConfirmed": 120102,
        "NewDeaths": 354,
        "TotalDeaths": 14053,
        "NewRecovered": 3858,
        "TotalRecovered": 87633,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Moldova",
        "CountryCode": "MD",
        "Slug": "moldova",
        "NewConfirmed": 107,
        "TotalConfirmed": 9807,
        "NewDeaths": 12,
        "TotalDeaths": 353,
        "NewRecovered": 100,
        "TotalRecovered": 5738,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Monaco",
        "CountryCode": "MC",
        "Slug": "monaco",
        "NewConfirmed": 0,
        "TotalConfirmed": 99,
        "NewDeaths": 0,
        "TotalDeaths": 4,
        "NewRecovered": 0,
        "TotalRecovered": 93,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Mongolia",
        "CountryCode": "MN",
        "Slug": "mongolia",
        "NewConfirmed": 1,
        "TotalConfirmed": 194,
        "NewDeaths": 0,
        "TotalDeaths": 0,
        "NewRecovered": 0,
        "TotalRecovered": 75,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Montenegro",
        "CountryCode": "ME",
        "Slug": "montenegro",
        "NewConfirmed": 0,
        "TotalConfirmed": 324,
        "NewDeaths": 0,
        "TotalDeaths": 9,
        "NewRecovered": 0,
        "TotalRecovered": 315,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Morocco",
        "CountryCode": "MA",
        "Slug": "morocco",
        "NewConfirmed": 78,
        "TotalConfirmed": 8302,
        "NewDeaths": 0,
        "TotalDeaths": 208,
        "NewRecovered": 44,
        "TotalRecovered": 7408,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Mozambique",
        "CountryCode": "MZ",
        "Slug": "mozambique",
        "NewConfirmed": 9,
        "TotalConfirmed": 433,
        "NewDeaths": 0,
        "TotalDeaths": 2,
        "NewRecovered": 4,
        "TotalRecovered": 131,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Myanmar",
        "CountryCode": "MM",
        "Slug": "myanmar",
        "NewConfirmed": 2,
        "TotalConfirmed": 244,
        "NewDeaths": 0,
        "TotalDeaths": 6,
        "NewRecovered": 3,
        "TotalRecovered": 159,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Namibia",
        "CountryCode": "NA",
        "Slug": "namibia",
        "NewConfirmed": 2,
        "TotalConfirmed": 31,
        "NewDeaths": 0,
        "TotalDeaths": 0,
        "NewRecovered": 0,
        "TotalRecovered": 16,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Nepal",
        "CountryCode": "NP",
        "Slug": "nepal",
        "NewConfirmed": 314,
        "TotalConfirmed": 3762,
        "NewDeaths": 1,
        "TotalDeaths": 14,
        "NewRecovered": 21,
        "TotalRecovered": 488,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Netherlands",
        "CountryCode": "NL",
        "Slug": "netherlands",
        "NewConfirmed": 165,
        "TotalConfirmed": 47945,
        "NewDeaths": 3,
        "TotalDeaths": 6035,
        "NewRecovered": 0,
        "TotalRecovered": 181,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "New Zealand",
        "CountryCode": "NZ",
        "Slug": "new-zealand",
        "NewConfirmed": 0,
        "TotalConfirmed": 1504,
        "NewDeaths": 0,
        "TotalDeaths": 22,
        "NewRecovered": 0,
        "TotalRecovered": 1482,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Nicaragua",
        "CountryCode": "NI",
        "Slug": "nicaragua",
        "NewConfirmed": 0,
        "TotalConfirmed": 1118,
        "NewDeaths": 0,
        "TotalDeaths": 46,
        "NewRecovered": 0,
        "TotalRecovered": 370,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Niger",
        "CountryCode": "NE",
        "Slug": "niger",
        "NewConfirmed": 0,
        "TotalConfirmed": 973,
        "NewDeaths": 0,
        "TotalDeaths": 65,
        "NewRecovered": 2,
        "TotalRecovered": 869,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Nigeria",
        "CountryCode": "NG",
        "Slug": "nigeria",
        "NewConfirmed": 315,
        "TotalConfirmed": 12801,
        "NewDeaths": 7,
        "TotalDeaths": 361,
        "NewRecovered": 81,
        "TotalRecovered": 4040,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Norway",
        "CountryCode": "NO",
        "Slug": "norway",
        "NewConfirmed": 14,
        "TotalConfirmed": 8561,
        "NewDeaths": 1,
        "TotalDeaths": 239,
        "NewRecovered": 0,
        "TotalRecovered": 8138,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Oman",
        "CountryCode": "OM",
        "Slug": "oman",
        "NewConfirmed": 604,
        "TotalConfirmed": 17486,
        "NewDeaths": 6,
        "TotalDeaths": 81,
        "NewRecovered": 342,
        "TotalRecovered": 3793,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Pakistan",
        "CountryCode": "PK",
        "Slug": "pakistan",
        "NewConfirmed": 9374,
        "TotalConfirmed": 108317,
        "NewDeaths": 170,
        "TotalDeaths": 2172,
        "NewRecovered": 1553,
        "TotalRecovered": 35018,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Palestinian Territory",
        "CountryCode": "PS",
        "Slug": "palestine",
        "NewConfirmed": 1,
        "TotalConfirmed": 473,
        "NewDeaths": 0,
        "TotalDeaths": 3,
        "NewRecovered": 1,
        "TotalRecovered": 404,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Panama",
        "CountryCode": "PA",
        "Slug": "panama",
        "NewConfirmed": 429,
        "TotalConfirmed": 16854,
        "NewDeaths": 5,
        "TotalDeaths": 398,
        "NewRecovered": 183,
        "TotalRecovered": 10401,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Papua New Guinea",
        "CountryCode": "PG",
        "Slug": "papua-new-guinea",
        "NewConfirmed": 0,
        "TotalConfirmed": 8,
        "NewDeaths": 0,
        "TotalDeaths": 0,
        "NewRecovered": 0,
        "TotalRecovered": 8,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Paraguay",
        "CountryCode": "PY",
        "Slug": "paraguay",
        "NewConfirmed": 10,
        "TotalConfirmed": 1145,
        "NewDeaths": 0,
        "TotalDeaths": 11,
        "NewRecovered": 28,
        "TotalRecovered": 603,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Peru",
        "CountryCode": "PE",
        "Slug": "peru",
        "NewConfirmed": 3181,
        "TotalConfirmed": 199696,
        "NewDeaths": 106,
        "TotalDeaths": 5571,
        "NewRecovered": 3337,
        "TotalRecovered": 89556,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Philippines",
        "CountryCode": "PH",
        "Slug": "philippines",
        "NewConfirmed": 579,
        "TotalConfirmed": 22474,
        "NewDeaths": 8,
        "TotalDeaths": 1011,
        "NewRecovered": 107,
        "TotalRecovered": 4637,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Poland",
        "CountryCode": "PL",
        "Slug": "poland",
        "NewConfirmed": 599,
        "TotalConfirmed": 27160,
        "NewDeaths": 9,
        "TotalDeaths": 1166,
        "NewRecovered": 143,
        "TotalRecovered": 12998,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Portugal",
        "CountryCode": "PT",
        "Slug": "portugal",
        "NewConfirmed": 192,
        "TotalConfirmed": 34885,
        "NewDeaths": 6,
        "TotalDeaths": 1485,
        "NewRecovered": 161,
        "TotalRecovered": 21156,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Qatar",
        "CountryCode": "QA",
        "Slug": "qatar",
        "NewConfirmed": 1368,
        "TotalConfirmed": 70158,
        "NewDeaths": 3,
        "TotalDeaths": 57,
        "NewRecovered": 1597,
        "TotalRecovered": 45935,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Republic of Kosovo",
        "CountryCode": "XK",
        "Slug": "kosovo",
        "NewConfirmed": 121,
        "TotalConfirmed": 1263,
        "NewDeaths": 1,
        "TotalDeaths": 31,
        "NewRecovered": 41,
        "TotalRecovered": 912,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Romania",
        "CountryCode": "RO",
        "Slug": "romania",
        "NewConfirmed": 125,
        "TotalConfirmed": 20604,
        "NewDeaths": 6,
        "TotalDeaths": 1339,
        "NewRecovered": 188,
        "TotalRecovered": 14826,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Russian Federation",
        "CountryCode": "RU",
        "Slug": "russia",
        "NewConfirmed": 8970,
        "TotalConfirmed": 476043,
        "NewDeaths": 112,
        "TotalDeaths": 5963,
        "NewRecovered": 3954,
        "TotalRecovered": 230226,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Rwanda",
        "CountryCode": "RW",
        "Slug": "rwanda",
        "NewConfirmed": 12,
        "TotalConfirmed": 451,
        "NewDeaths": 0,
        "TotalDeaths": 2,
        "NewRecovered": 7,
        "TotalRecovered": 297,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Saint Kitts and Nevis",
        "CountryCode": "KN",
        "Slug": "saint-kitts-and-nevis",
        "NewConfirmed": 0,
        "TotalConfirmed": 15,
        "NewDeaths": 0,
        "TotalDeaths": 0,
        "NewRecovered": 0,
        "TotalRecovered": 15,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Saint Lucia",
        "CountryCode": "LC",
        "Slug": "saint-lucia",
        "NewConfirmed": 0,
        "TotalConfirmed": 19,
        "NewDeaths": 0,
        "TotalDeaths": 0,
        "NewRecovered": 0,
        "TotalRecovered": 18,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Saint Vincent and Grenadines",
        "CountryCode": "VC",
        "Slug": "saint-vincent-and-the-grenadines",
        "NewConfirmed": 0,
        "TotalConfirmed": 27,
        "NewDeaths": 0,
        "TotalDeaths": 0,
        "NewRecovered": 0,
        "TotalRecovered": 16,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "San Marino",
        "CountryCode": "SM",
        "Slug": "san-marino",
        "NewConfirmed": 7,
        "TotalConfirmed": 687,
        "NewDeaths": 0,
        "TotalDeaths": 42,
        "NewRecovered": 50,
        "TotalRecovered": 478,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Sao Tome and Principe",
        "CountryCode": "ST",
        "Slug": "sao-tome-and-principe",
        "NewConfirmed": 0,
        "TotalConfirmed": 513,
        "NewDeaths": 0,
        "TotalDeaths": 12,
        "NewRecovered": 0,
        "TotalRecovered": 68,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Saudi Arabia",
        "CountryCode": "SA",
        "Slug": "saudi-arabia",
        "NewConfirmed": 3369,
        "TotalConfirmed": 105283,
        "NewDeaths": 34,
        "TotalDeaths": 746,
        "NewRecovered": 1707,
        "TotalRecovered": 74524,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Senegal",
        "CountryCode": "SN",
        "Slug": "senegal",
        "NewConfirmed": 99,
        "TotalConfirmed": 4427,
        "NewDeaths": 0,
        "TotalDeaths": 49,
        "NewRecovered": 111,
        "TotalRecovered": 2699,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Serbia",
        "CountryCode": "RS",
        "Slug": "serbia",
        "NewConfirmed": 73,
        "TotalConfirmed": 11896,
        "NewDeaths": 1,
        "TotalDeaths": 250,
        "NewRecovered": 0,
        "TotalRecovered": 11348,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Seychelles",
        "CountryCode": "SC",
        "Slug": "seychelles",
        "NewConfirmed": 0,
        "TotalConfirmed": 11,
        "NewDeaths": 0,
        "TotalDeaths": 0,
        "NewRecovered": 0,
        "TotalRecovered": 11,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Sierra Leone",
        "CountryCode": "SL",
        "Slug": "sierra-leone",
        "NewConfirmed": 32,
        "TotalConfirmed": 1001,
        "NewDeaths": 1,
        "TotalDeaths": 49,
        "NewRecovered": 3,
        "TotalRecovered": 611,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Singapore",
        "CountryCode": "SG",
        "Slug": "singapore",
        "NewConfirmed": 386,
        "TotalConfirmed": 38296,
        "NewDeaths": 0,
        "TotalDeaths": 25,
        "NewRecovered": 482,
        "TotalRecovered": 25368,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Slovakia",
        "CountryCode": "SK",
        "Slug": "slovakia",
        "NewConfirmed": 2,
        "TotalConfirmed": 1530,
        "NewDeaths": 0,
        "TotalDeaths": 28,
        "NewRecovered": 7,
        "TotalRecovered": 1396,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Slovenia",
        "CountryCode": "SI",
        "Slug": "slovenia",
        "NewConfirmed": 0,
        "TotalConfirmed": 1485,
        "NewDeaths": 0,
        "TotalDeaths": 109,
        "NewRecovered": 0,
        "TotalRecovered": 1359,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Somalia",
        "CountryCode": "SO",
        "Slug": "somalia",
        "NewConfirmed": 34,
        "TotalConfirmed": 2368,
        "NewDeaths": 1,
        "TotalDeaths": 84,
        "NewRecovered": 29,
        "TotalRecovered": 470,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "South Africa",
        "CountryCode": "ZA",
        "Slug": "south-africa",
        "NewConfirmed": 2594,
        "TotalConfirmed": 50879,
        "NewDeaths": 82,
        "TotalDeaths": 1080,
        "NewRecovered": 1735,
        "TotalRecovered": 26099,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "South Sudan",
        "CountryCode": "SS",
        "Slug": "south-sudan",
        "NewConfirmed": 287,
        "TotalConfirmed": 1604,
        "NewDeaths": 5,
        "TotalDeaths": 19,
        "NewRecovered": 9,
        "TotalRecovered": 15,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Spain",
        "CountryCode": "ES",
        "Slug": "spain",
        "NewConfirmed": 167,
        "TotalConfirmed": 241717,
        "NewDeaths": 0,
        "TotalDeaths": 27136,
        "NewRecovered": 0,
        "TotalRecovered": 150376,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Sri Lanka",
        "CountryCode": "LK",
        "Slug": "sri-lanka",
        "NewConfirmed": 22,
        "TotalConfirmed": 1857,
        "NewDeaths": 0,
        "TotalDeaths": 11,
        "NewRecovered": 49,
        "TotalRecovered": 990,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Sudan",
        "CountryCode": "SD",
        "Slug": "sudan",
        "NewConfirmed": 161,
        "TotalConfirmed": 6242,
        "NewDeaths": 13,
        "TotalDeaths": 372,
        "NewRecovered": 45,
        "TotalRecovered": 2059,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Suriname",
        "CountryCode": "SR",
        "Slug": "suriname",
        "NewConfirmed": 6,
        "TotalConfirmed": 128,
        "NewDeaths": 1,
        "TotalDeaths": 2,
        "NewRecovered": 0,
        "TotalRecovered": 9,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Swaziland",
        "CountryCode": "SZ",
        "Slug": "swaziland",
        "NewConfirmed": 7,
        "TotalConfirmed": 340,
        "NewDeaths": 0,
        "TotalDeaths": 3,
        "NewRecovered": 4,
        "TotalRecovered": 229,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Sweden",
        "CountryCode": "SE",
        "Slug": "sweden",
        "NewConfirmed": 403,
        "TotalConfirmed": 45133,
        "NewDeaths": 35,
        "TotalDeaths": 4694,
        "NewRecovered": 0,
        "TotalRecovered": 0,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Switzerland",
        "CountryCode": "CH",
        "Slug": "switzerland",
        "NewConfirmed": 7,
        "TotalConfirmed": 30972,
        "NewDeaths": 2,
        "TotalDeaths": 1923,
        "NewRecovered": 0,
        "TotalRecovered": 28700,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Syrian Arab Republic (Syria)",
        "CountryCode": "SY",
        "Slug": "syria",
        "NewConfirmed": 3,
        "TotalConfirmed": 144,
        "NewDeaths": 0,
        "TotalDeaths": 6,
        "NewRecovered": 4,
        "TotalRecovered": 62,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Taiwan, Republic of China",
        "CountryCode": "TW",
        "Slug": "taiwan",
        "NewConfirmed": 0,
        "TotalConfirmed": 443,
        "NewDeaths": 0,
        "TotalDeaths": 7,
        "NewRecovered": 0,
        "TotalRecovered": 430,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Tajikistan",
        "CountryCode": "TJ",
        "Slug": "tajikistan",
        "NewConfirmed": 80,
        "TotalConfirmed": 4609,
        "NewDeaths": 0,
        "TotalDeaths": 48,
        "NewRecovered": 90,
        "TotalRecovered": 2763,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Tanzania, United Republic of",
        "CountryCode": "TZ",
        "Slug": "tanzania",
        "NewConfirmed": 0,
        "TotalConfirmed": 509,
        "NewDeaths": 0,
        "TotalDeaths": 21,
        "NewRecovered": 0,
        "TotalRecovered": 183,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Thailand",
        "CountryCode": "TH",
        "Slug": "thailand",
        "NewConfirmed": 7,
        "TotalConfirmed": 3119,
        "NewDeaths": 0,
        "TotalDeaths": 58,
        "NewRecovered": 1,
        "TotalRecovered": 2973,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Timor-Leste",
        "CountryCode": "TL",
        "Slug": "timor-leste",
        "NewConfirmed": 0,
        "TotalConfirmed": 24,
        "NewDeaths": 0,
        "TotalDeaths": 0,
        "NewRecovered": 0,
        "TotalRecovered": 24,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Togo",
        "CountryCode": "TG",
        "Slug": "togo",
        "NewConfirmed": 2,
        "TotalConfirmed": 497,
        "NewDeaths": 0,
        "TotalDeaths": 13,
        "NewRecovered": 3,
        "TotalRecovered": 251,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Trinidad and Tobago",
        "CountryCode": "TT",
        "Slug": "trinidad-and-tobago",
        "NewConfirmed": 0,
        "TotalConfirmed": 117,
        "NewDeaths": 0,
        "TotalDeaths": 8,
        "NewRecovered": 1,
        "TotalRecovered": 109,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Tunisia",
        "CountryCode": "TN",
        "Slug": "tunisia",
        "NewConfirmed": 0,
        "TotalConfirmed": 1087,
        "NewDeaths": 0,
        "TotalDeaths": 49,
        "NewRecovered": 0,
        "TotalRecovered": 982,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Turkey",
        "CountryCode": "TR",
        "Slug": "turkey",
        "NewConfirmed": 989,
        "TotalConfirmed": 171121,
        "NewDeaths": 19,
        "TotalDeaths": 4711,
        "NewRecovered": 3411,
        "TotalRecovered": 141380,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Uganda",
        "CountryCode": "UG",
        "Slug": "uganda",
        "NewConfirmed": 30,
        "TotalConfirmed": 646,
        "NewDeaths": 0,
        "TotalDeaths": 0,
        "NewRecovered": 7,
        "TotalRecovered": 103,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Ukraine",
        "CountryCode": "UA",
        "Slug": "ukraine",
        "NewConfirmed": 478,
        "TotalConfirmed": 28077,
        "NewDeaths": 9,
        "TotalDeaths": 805,
        "NewRecovered": 144,
        "TotalRecovered": 12657,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "United Arab Emirates",
        "CountryCode": "AE",
        "Slug": "united-arab-emirates",
        "NewConfirmed": 568,
        "TotalConfirmed": 39376,
        "NewDeaths": 5,
        "TotalDeaths": 281,
        "NewRecovered": 469,
        "TotalRecovered": 22275,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "United Kingdom",
        "CountryCode": "GB",
        "Slug": "united-kingdom",
        "NewConfirmed": 1213,
        "TotalConfirmed": 288834,
        "NewDeaths": 55,
        "TotalDeaths": 40680,
        "NewRecovered": 16,
        "TotalRecovered": 1255,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "United States of America",
        "CountryCode": "US",
        "Slug": "united-states",
        "NewConfirmed": 18534,
        "TotalConfirmed": 1960897,
        "NewDeaths": 476,
        "TotalDeaths": 110990,
        "NewRecovered": 12155,
        "TotalRecovered": 518522,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Uruguay",
        "CountryCode": "UY",
        "Slug": "uruguay",
        "NewConfirmed": 0,
        "TotalConfirmed": 845,
        "NewDeaths": 0,
        "TotalDeaths": 23,
        "NewRecovered": 8,
        "TotalRecovered": 738,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Uzbekistan",
        "CountryCode": "UZ",
        "Slug": "uzbekistan",
        "NewConfirmed": 109,
        "TotalConfirmed": 4440,
        "NewDeaths": 1,
        "TotalDeaths": 18,
        "NewRecovered": 3,
        "TotalRecovered": 3357,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Venezuela (Bolivarian Republic)",
        "CountryCode": "VE",
        "Slug": "venezuela",
        "NewConfirmed": 96,
        "TotalConfirmed": 2473,
        "NewDeaths": 0,
        "TotalDeaths": 22,
        "NewRecovered": 0,
        "TotalRecovered": 487,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Viet Nam",
        "CountryCode": "VN",
        "Slug": "vietnam",
        "NewConfirmed": 1,
        "TotalConfirmed": 332,
        "NewDeaths": 0,
        "TotalDeaths": 0,
        "NewRecovered": 9,
        "TotalRecovered": 316,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Western Sahara",
        "CountryCode": "EH",
        "Slug": "western-sahara",
        "NewConfirmed": 0,
        "TotalConfirmed": 9,
        "NewDeaths": 0,
        "TotalDeaths": 1,
        "NewRecovered": 0,
        "TotalRecovered": 6,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Yemen",
        "CountryCode": "YE",
        "Slug": "yemen",
        "NewConfirmed": 12,
        "TotalConfirmed": 496,
        "NewDeaths": 0,
        "TotalDeaths": 112,
        "NewRecovered": 0,
        "TotalRecovered": 23,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Zambia",
        "CountryCode": "ZM",
        "Slug": "zambia",
        "NewConfirmed": 111,
        "TotalConfirmed": 1200,
        "NewDeaths": 3,
        "TotalDeaths": 10,
        "NewRecovered": 0,
        "TotalRecovered": 912,
        "Date": "2020-06-09T09:57:08Z"
      },
      {
        "Country": "Zimbabwe",
        "CountryCode": "ZW",
        "Slug": "zimbabwe",
        "NewConfirmed": 5,
        "TotalConfirmed": 287,
        "NewDeaths": 0,
        "TotalDeaths": 4,
        "NewRecovered": 12,
        "TotalRecovered": 46,
        "Date": "2020-06-09T09:57:08Z"
      }
    ],
    "Date": "2020-06-09T09:57:08Z"
  }